In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("../dataset/Fraud detection Dataset.csv")
df.head()

  transaction_id user_id  transaction_amount  ... txn_hour is_weekend is_fraud
0       T0086548   U9625             5068.33  ...        2          0        0
1       T0088155   U9783             3428.09  ...        7          1        0
2       T0076282   U8629             5161.81  ...       16          1        0
3       T0013138   U2319             4242.40  ...        1          0        0
4       T0060581   U7056             1721.96  ...        6          0        0

[5 rows x 18 columns]

In [5]:
# since the number of unique values in transaction_id and the number of columns present in the dataset are the same
# this implies there are unique transaction id for all the transactions 
# this means there is no predictive power in this column and hence can be removed
df.drop(["transaction_id"], axis = 1, inplace = True)

In [6]:
#since every user id starts with u, we remove this and keep it ready for one hot encoding
df["user_id"] = df["user_id"].str[1:]
df.head()

  user_id  transaction_amount transaction_type  ... txn_hour is_weekend  is_fraud
0    9625             5068.33             NEFT  ...        2          0         0
1    9783             3428.09             IMPS  ...        7          1         0
2    8629             5161.81             NEFT  ...       16          1         0
3    2319             4242.40              UPI  ...        1          0         0
4    7056             1721.96              UPI  ...        6          0         0

[5 rows x 17 columns]

In [7]:
# transaction amount can be scaled
#transaction type must be one hot encoded
# location must also be one hot encoded
# device is also one hot encoded
# others can be scaled if it involves categorical number

In [8]:
df["transaction_time"] = pd.to_datetime(df["transaction_time"], dayfirst=True)

In [9]:
df["time"] = df["transaction_time"].dt.time
df["date"] = df["transaction_time"].dt.date

In [10]:
df.drop(["transaction_time"], axis = 1, inplace = True)

In [11]:
df["account_age_yrs"] = (df["account_age_days"]/ 365).astype(int)
df["account_age_yrs"].unique()

array([8, 6, 3, 1, 7, 0, 2, 9, 5, 4])

In [12]:
df["is_fraud"].value_counts()
#dataset is severly unbalanced - splitting must be done in such a way that the training must have approx equal number of 1s and 0s

is_fraud
0    90168
1    10018
Name: count, dtype: int64

In [13]:
df.drop(["account_age_days"], axis = 1, inplace = True)
df.head()

  user_id  transaction_amount  ...        date account_age_yrs
0    9625             5068.33  ...  2024-09-25               8
1    9783             3428.09  ...  2024-06-23               6
2    8629             5161.81  ...  2024-06-02               3
3    2319             4242.40  ...  2024-01-30               1
4    7056             1721.96  ...  2024-07-02               1

[5 rows x 18 columns]

In [14]:
df["date"] = pd.to_datetime(df["date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100186 entries, 0 to 100185
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   user_id                 100186 non-null  object
 1   transaction_amount      100186 non-null  float64
 2   transaction_type        100186 non-null  object
 3   location                100186 non-null  object
 4   is_foreign_transaction  100186 non-null  int64
 5   device_type             100186 non-null  object
 6   is_new_device           100186 non-null  int64
 7   is_new_location         100186 non-null  int64
 8   avg_transaction_amount  100186 non-null  float64
 9   transactions_last_24h   100186 non-null  int64
 10  failed_logins_24h       100186 non-null  int64
 11  time_since_last_txn     100186 non-null  int64
 12  txn_hour                100186 non-null  int64
 13  is_weekend              100186 non-null  int64
 14  is_fraud                100186 non-null  int64
 15  time                    100186 non-null  object
 16  date                    100186 non-null  datetime64[ns]
 17  account_age_yrs         100186 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(10), object(5)
memory usage: 13.8+ MB

In [15]:
from sklearn.model_selection import train_test_split

x = df.drop(["is_fraud"], axis = 1)
y = df["is_fraud"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=0.5, random_state = 42)

In [16]:
print(len(y_train[y_train == 1])/ len(x_train))
print(len(y_train[y_train == 0])/ len(x_train))

0.09905889063168402
0.900941109368316

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

transformer = ColumnTransformer([
    ("trf1", StandardScaler(), ["transaction_amount", "avg_transaction_amount","time_since_last_txn"]),
    ("trf2", OneHotEncoder(drop = "first", sparse_output = False, handle_unknown="ignore"), ["user_id", "transaction_type", "location", "device_type", "txn_hour", "time", "date", "account_age_yrs"]),
    
], remainder = "passthrough")

In [18]:
x_train = transformer.fit_transform(x_train)
x_test = transformer.transform(x_test)

c:\Users\Nadakishore\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [19]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state = 42)
x_train, y_train = sm.fit_resample(x_train, y_train)

In [20]:
print(len(y_train[y_train == 1])/ len(x_train))
print(len(y_train[y_train == 0])/ len(x_train))

0.5
0.5

In [21]:
len(x_train)

126366

In [22]:
print(len(y_test[y_test == 1])/ len(x_test))
print(len(y_test[y_test == 0])/ len(x_test))

0.10340697364918819
0.8965930263508118

In [23]:
from sklearn.ensemble import RandomForestClassifier

model1 = RandomForestClassifier(max_depth = 10, n_jobs = -1)
model1.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, n_jobs=-1)

In [24]:
pred = model1.predict_proba(x_test)[:, 1]
pred = (pred >= 0.494).astype(int)

In [25]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print(accuracy_score(y_test, pred))
print(f1_score(y_test, pred))
print(precision_score(y_test, pred))
print(recall_score(y_test, pred))
print(confusion_matrix(y_test,pred))

0.9284668618578653
0.6835443037974683
0.6299511665762344
0.747104247104247
[[12792   682]
 [  393  1161]]

In [26]:
x_val = transformer.transform(x_val)

c:\Users\Nadakishore\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [27]:
predict = model1.predict_proba(x_val)[:, 1]
pred = (predict >= 0.494).astype(int)

In [28]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print(accuracy_score(y_val, pred))
print(f1_score(y_val, pred))
print(precision_score(y_val, pred))
print(recall_score(y_val, pred))
print(confusion_matrix(y_val,pred))

0.9293319137609795
0.6795413397706699
0.6265998887033946
0.7422544495715228
[[12840   671]
 [  391  1126]]

In [29]:
import pickle

file = open("model.pkl", "wb")
pickle.dump(model1, file)
file.close()

In [30]:
file = open("preprocessing.pkl", "wb")
pickle.dump(transformer, file)
file.close()

In [31]:
import xgboost as xgb 

model2 = xgb.XGBClassifier()
model2.fit(x_train, y_train)
pred = model2.predict(x_test)

In [33]:
predict = model2.predict_proba(x_test)[:, 1]
pred = (predict >= 0.494).astype(int)

In [34]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print(accuracy_score(y_test, pred))
print(f1_score(y_test, pred))
print(precision_score(y_test, pred))
print(recall_score(y_test, pred))
print(confusion_matrix(y_test,pred))

0.9752462070801171
0.8664752333094041
0.9797077922077922
0.7767052767052767
[[13449    25]
 [  347  1207]]

In [35]:
predict = model2.predict_proba(x_val)[:, 1]
pred = (predict >= 0.494).astype(int)

In [36]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print(accuracy_score(y_val, pred))
print(f1_score(y_val, pred))
print(precision_score(y_val, pred))
print(recall_score(y_val, pred))
print(confusion_matrix(y_val,pred))

0.9757785467128027
0.8667642752562226
0.974485596707819
0.7804878048780488
[[13480    31]
 [  333  1184]]

In [37]:
import pickle

file = open("model.pkl", "wb")
pickle.dump(model2, file)
file.close()